### PR TITLE
Switch to avh4/elm-color type.

### PR DESCRIPTION
**Pull request by RalfNorthman**
As talked about in #1.

### CODE REVIEW

**Comment by dawehner** [comment]
I'm curious, I don't see the generate.js being changed. Is there a reason for that? I would have expected that to change given the new code is different too.

**Comment by RalfNorthman** [comment]
The files in src/Colorbrewer is as they were before your latest push, except that I searched-and-replaced all occurrences of `rgb` with `rgb255`. 

The Color package from 0.18 used ints from 0 to 255 as standard, while the new elm-color uses floats between 0 and 1. Therefore I had to use a slightly different function.

I'm not a JavaScript guy, so I didn't mess with that.

**Comment by dawehner** [comment]
Hei. Well, I generated the files automatically. It would be nice if we
could keep doing that as it reduces the chance for errors.

**Comment by RalfNorthman** [comment]
Well, they *are* your generated files except one automatically searched-and-replaced word (with the Vim text editor). If I would generate code from the json I would probably use Elixir. 

I probably *could* alter the old js file to use `rgb255` instead of `rgb` and regenerate the files with that, but that feels like some unnecessary hoops to jump through.

**Comment by dawehner** [comment]
Feel free to replace the JS file with whatever works for you :) I just
think the automation is nice

**Comment by dawehner** [comment]
@RalfNorthman I've implemented the same change by adapting the generate.js file.
Thanks a lot for your work and  your especially the discussion we had. I've released a 4.0.0 version.

**Pull request closed without merging**
