### PR TITLE
Upgrade to 0.19

### PR DESCRIPTION
**Pull request by RalfNorthman**
Discussion in issue #1.

### CODE REVIEW

**Comment by dawehner** [comment]
I'm sorry I totally forgot to push my latest code changes. :| The code should now be up to date to 0.19 at least

**Comment by dawehner** [comment]
It would be nice to adapt the ```generate.js``` | revert it back to the 2.0 version I guess

**Comment by RalfNorthman** [comment]
Had you already upgraded to 0.19 locally and forgot about it!?

**Comment by dawehner** [comment]
I've updated locally and pushed it to package.elm but forgot to push it to
github I fear. The commit history should have that. On the other hand, it
deals like a big of the elm package system, shouldn't be possible, right?

**Comment by RalfNorthman** [comment]
Fortunately, it was not a ton of work, so it's not a big deal. :-)

**Pull request closed without merging**
